services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: habitax
        restart: unless-stopped
        volumes:
            - storage_data:/var/www/storage
        depends_on:
            - postgres
            - redis
        networks:
            - internal

    web:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./public:/var/www/public
            - storage_data:/var/www/storage
        depends_on:
            - app
        networks:
            - internal

    postgres:
        image: postgres:alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: habitax
            POSTGRES_PASSWORD: habitax
            POSTGRES_DB: habitax
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - internal
        ports:
            - "5432:5432"

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - internal
        ports:
            - "6379:6379"

    traefik:
        image: traefik:v2.10
        container_name: traefik
        command:
            - "--api.insecure=false"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8081:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    postgres_data:
        driver: local
    storage_data:
        driver: local
