services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: habitax
        restart: unless-stopped
        volumes:
            - ./storage:/var/www/storage
            - ./public:/var/www/public
        depends_on:
            - redis
        networks:
            - internal

    web:
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./storage:/var/www/storage
            - ./public:/var/www/public
        depends_on:
            - app
        networks:
            - internal

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - internal
        ports:
            - "6379:6379"

    traefik:
        image: traefik:v2.10
        container_name: traefik
        command:
            - "--api.insecure=false"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8081:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal

#    cloudflared:
#        image: cloudflare/cloudflared:latest
#        container_name: cloudflared
#        command: tunnel --no-autoupdate run --token eyJhIjoiMzUzMmVlZDcwMGQxZjYzZjhkZTY0YmE1ZjUwYTY4ZjIiLCJ0IjoiNDg0NDAxNmQtZjQ1MC00YmE2LTljNGMtMmI3N2ZkZDMzOGU0IiwicyI6IlpUQXlZall3TXpNdFkyTTJPUzAwTURjMkxUZ3daVE10WkdNeU1tTTJOVFprTWpBNCJ9
#        networks:
#            - internal
#        restart: unless-stopped

networks:
    internal:
        driver: bridge
